# Generated by Django 4.1.5 on 2023-01-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_asal_sekolah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='alamat',
            new_name='Alamat',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='asal_sekolah',
            new_name='AsalSekolah',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='hp',
            new_name='Hp',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='jenis_kelamin',
            new_name='JenisKelamin',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='nisn',
            new_name='NISN',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='nama',
            new_name='Nama',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='tanggal_lahir',
            new_name='TanggalLahir',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='tempat_lahir',
            new_name='TempatLahir',
        ),
    ]
