# Generated by Django 4.1.5 on 2023-01-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_rename_asalsekolah_siswa_asal_sekolah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='Tanggal_Lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
