# Generated by Django 4.1.5 on 2023-01-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sekolah',
            old_name='alamat',
            new_name='Alamat',
        ),
        migrations.RenameField(
            model_name='sekolah',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='sekolah',
            old_name='hp',
            new_name='Hp',
        ),
        migrations.RenameField(
            model_name='sekolah',
            old_name='jenis_sekolah',
            new_name='Jenis_Sekolah',
        ),
        migrations.RenameField(
            model_name='sekolah',
            old_name='nama',
            new_name='Nama',
        ),
        migrations.RenameField(
            model_name='sekolah',
            old_name='web',
            new_name='Web',
        ),
    ]
