# Generated by Django 4.1.5 on 2023-01-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_alter_sekolah_npsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='Status',
            field=models.CharField(choices=[('Swasta', 'Swasta'), ('Negeri', 'Negeri')], default='0', max_length=10),
        ),
    ]
