# Generated by Django 4.1.5 on 2023-01-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('hp', models.CharField(max_length=20)),
                ('alamat', models.TextField(max_length=100)),
                ('jenis_perusahaan', models.CharField(choices=[('PT', 'PT'), ('CV', 'CV'), ('F', 'Firma'), ('K', 'Koperasi'), ('PR', 'Persero'), ('PG', 'Perseorangan')], max_length=2)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
