# Generated by Django 4.1.5 on 2023-01-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0002_rename_alamat_perusahaan_alamat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perusahaan',
            name='Web',
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='Bidang_Perusahaan',
            field=models.CharField(choices=[('PE', 'Perusahaan Ekstraktif'), ('PA', 'Perusahaan Agraris'), ('PD', 'Perusahaan Dagang'), ('PJ', 'Perusahaan Jasa'), ('PI', 'Perusahaan Industri')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='Jenis_Perusahaan',
            field=models.CharField(choices=[('PT', 'PT'), ('CV', 'CV'), ('F', 'Firma'), ('K', 'Koperasi'), ('PR', 'Persero'), ('PG', 'Perseorangan'), ('PM', 'Pemerintahan')], max_length=2),
        ),
    ]
