# Generated by Django 4.1.5 on 2023-01-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perusahaan', '0005_alter_perusahaan_alamat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perusahaan',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='perusahaan',
            old_name='Nama',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='perusahaan',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='Alamat',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='Bidang_Perusahaan',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='Hp',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='Jenis_Perusahaan',
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='bidang',
            field=models.CharField(blank=True, choices=[('PE', 'Perusahaan Ekstraktif'), ('PA', 'Perusahaan Agraris'), ('PD', 'Perusahaan Dagang'), ('PJ', 'Perusahaan Jasa'), ('PI', 'Perusahaan Industri')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perusahaan_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('KBTU', 'Kabag TU')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='kategori',
            field=models.CharField(choices=[('Pem', 'Pemerintahan'), ('Neg', 'Negeri')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='nama_pic',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='no_tlp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='alamat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
