# Generated by Django 4.1.5 on 2023-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0006_rename_create_at_perusahaan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='bidang',
            field=models.CharField(blank=True, choices=[('Perusahaan Ekstraktif', 'Perusahaan Ekstraktif'), ('Perusahaan Agraris', 'Perusahaan Agraris'), ('Perusahaan Dagang', 'Perusahaan Dagang'), ('Perusahaan Jasa', 'Perusahaan Jasa'), ('Perusahaan Industri', 'Perusahaan Industri')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Kabag TU', 'Kabag TU')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='kategori',
            field=models.CharField(choices=[('Pemerintahan', 'Pemerintahan'), ('Negeri', 'Negeri')], default='', max_length=20),
        ),
    ]
